# Generated by Django 4.0.3 on 2022-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoservice', '0002_order_service_alter_car_car_model_id_orderrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
    ]
